from ..html_elements import _HTMLElement

Address = _HTMLElement("address")
Article = _HTMLElement("article")
Aside = _HTMLElement("aside")
Footer = _HTMLElement("footer")
Header = _HTMLElement("header")
H1 = _HTMLElement("h1")
H2 = _HTMLElement("h2")
H3 = _HTMLElement("h3")
H4 = _HTMLElement("h4")
H5 = _HTMLElement("h5")
H6 = _HTMLElement("h6")
Main = _HTMLElement("main")
Nav = _HTMLElement("nav")
Section = _HTMLElement("section")
