from ...escape import safe
from ..component import _Elem

A = _Elem("a")
Abbr = _Elem("abbr")
B = _Elem("b")
Bdi = _Elem("bdi")
Bdo = _Elem("bdo")
Br = safe("<br>")
Cite = _Elem("cite")
Code = _Elem("code")
Data = _Elem("data")
Del = _Elem("del")
Dfn = _Elem("dfn")
Em = _Elem("em")
I = _Elem("i")  # noqa: E741
Ins = _Elem("ins")
Kbd = _Elem("kbd")
Mark = _Elem("mark")
Q = _Elem("q")
Rp = _Elem("rp")
Rt = _Elem("rt")
Ruby = _Elem("ruby")
S = _Elem("s")
Samp = _Elem("samp")
Small = _Elem("small")
Span = _Elem("span")
Strong = _Elem("strong")
Sub = _Elem("sub")
Sup = _Elem("sup")
Time = _Elem("time")
U = _Elem("u")
Var = _Elem("var")
Wbr = safe("<wbr />")
