[project]
name = "compone"
version = "0.4.1"
description = "Component framework for Python"
license = "MIT"
readme = "README.md"
authors = [{ name = "György Kiss", email = "gyorgy@duck.com" }]
requires-python = ">=3.10"
dependencies = [
    "markupsafe>=3"
]

[tool.pytest.ini_options]
addopts = "--benchmark-disable"
testpaths = ["tests"]

[tool.basedpyright]
reportUnusedCallResult = false

[build-system]
requires = ["setuptools>=77", "setuptools-rust>=1.12,<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
py-modules = []
include-package-data = false

[[tool.setuptools-rust.ext-modules]]
target = "compone"
path = "Cargo.toml"
binding = "PyO3"
py-limited-api = true

[dependency-groups]
dev = [
    "jinja2>=3.1.5",
    "pytest-benchmark>=4.0.0",
]
