[project]
name = "compone"
version = "0.4.1"
description = "Component framework for Python"
license.text = "MIT"
readme = "README.md"
authors = [{ name = "György Kiss", email = "gyorgy@duck.com" }]
requires-python = ">=3.10"
dependencies = [
    "markupsafe>=3"
]

[tool.pytest.ini_options]
addopts = "--benchmark-disable"
testpaths = ["tests"]

[tool.basedpyright]
reportUnusedCallResult = false

[build-system]
requires = ["maturin>=1.11,<2"]
build-backend = "maturin"

[tool.maturin]
module-name = "compone.compone"
python-source = "."

[dependency-groups]
dev = [
    "jinja2>=3.1.5",
    "pytest-benchmark>=4.0.0",
]
