from ..component import Elem

Address = Elem("address")
Article = Elem("article")
Aside = Elem("aside")
Footer = Elem("footer")
Header = Elem("header")
H1 = Elem("h1")
H2 = Elem("h2")
H3 = Elem("h3")
H4 = Elem("h4")
H5 = Elem("h5")
H6 = Elem("h6")
Main = Elem("main")
Nav = Elem("nav")
Section = Elem("section")
