from .elements.content_sectioning import (
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Address,
    Article,
    Aside,
    Footer,
    Header,
    Main,
    Nav,
    Section,
)
from .elements.embedded import Embed, Iframe, Object, Picture, Portal, Source
from .elements.forms import (
    Button,
    ButtonButton,
    Datalist,
    Fieldset,
    Form,
    Input,
    Label,
    Legend,
    Meter,
    Optgroup,
    Option,
    Output,
    Progress,
    ResetButton,
    Select,
    SubmitButton,
    Textarea,
)
from .elements.inline_text import (
    A,
    Abbr,
    B,
    Bdi,
    Bdo,
    Br,
    Cite,
    Code,
    Data,
    Del,
    Dfn,
    Em,
    I,
    Ins,
    Kbd,
    Mark,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Small,
    Span,
    Strong,
    Sub,
    Sup,
    Time,
    U,
    Var,
    Wbr,
)
from .elements.interactive import Details, Dialog, Summary
from .elements.main import Body, Html
from .elements.metadata import Base, Head, Link, Meta, Style, Title
from .elements.multimedia import Area, Audio, Img, Map, Track, Video
from .elements.other import Math, Svg
from .elements.scripting import Canvas, Noscript, Script
from .elements.table import (
    Caption,
    Col,
    Colgroup,
    Table,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
)
from .elements.text_content import (
    Blockquote,
    Dd,
    Div,
    Dl,
    Dt,
    Figcaption,
    Figure,
    Hr,
    Li,
    Menu,
    Ol,
    P,
    Pre,
    Ul,
)
from .elements.web_components import Slot, Template
from .helpers import classes
