set tempdir := "/tmp"

help:
    @just --list

# Install npm dependencies
install:
    bun install

# Run linters and other checks
check:
    pre-commit run --all-files --hook-stage manual

# Generate stories.css with tailwind continuously, reloading when files changed
gencss:
    bun x tailwindcss -i stories.css -o compone_stories/static/stories.css --watch
