[tool.poetry]
name = "compone-stories"
version = "0.1.0"
description = "Storybook for Compone"
authors = ["György Kiss <kissgyorgy@me.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
