[project]
name = "compone-stories"
version = "0.1.0"
description = "Storybook for Compone"
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "hypercorn>=0.17.3",
    "starlette>=0.44.0",
    "watchfiles>=0.24.0",
]

[project.entry-points.'compone.cli']
stories = "compone_stories.cli:stories"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["compone_stories*"]
exclude = ["example_stories*"]
